= RBD Challenge

//++++
//<link rel="stylesheet"  href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/3.1.0/css/font-awesome.min.css">
//++++
:icons: font
:source-language: shell
:numbered:
// Activate experimental attribute for Keyboard Shortcut keys
:experimental:
:source-highlighter: pygments
:sectnums:
:sectnumlevels: 6
:toc: left
:toclevels: 4


== Create RBD Pool

Perform the following operations:

* Create a pool `newrbd`  to host some RBDs. The pool will use a replication factor of 2.
* Change the default RBD Image order to be 20
* Verify pool `rbd` exists. If not create it

== Create RBD Image

Perform the following operations in pool `newrbd`:

* Create a 256MiB RBD image `testimage`
* Check used space( # rbd -p rbdpool du newrbd/testimage )
* Format the RBD Image with `ext4`
* Copy the content of `/var/log` into the RBD Image in a directory called `batch1`
* Create a snapshot `snap1` for the RBD Image
* Copy the content of `/var/lib/alternatives/` into the RBD Image in a directory called `batch2`
* Create a snapshot `snap2` for the RBD Image

[NOTE]
====
If you get a full system, remember, you can extend rbd images online!
====

== Export and Import

Perform the following operations in pool `newrbd`:

* Export as a flat file the differences between the formatted RBD Image and `snap1`
* Export as a flat file the differences between `snap1` and `snap2`
* Import the differences you exported into a RBD Image named `target1` in pool `rbd`

== Clone

Perform the following operations, check space consuption on every step you take:

* Create a clone of `newrbd/testimage@snap2` in pool `rbdpool` and name it `clone1`
* Make the clone rbdpool/clone1 an independent RBD Image

== Cleanup

* Delete all RBD Images
* Delete all pools you have created
