= RBD Challenge

//++++
//<link rel="stylesheet"  href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/3.1.0/css/font-awesome.min.css">
//++++
:icons: font
:source-language: shell
:numbered:
// Activate experimental attribute for Keyboard Shortcut keys
:experimental:
:source-highlighter: pygments
:sectnums:
:sectnumlevels: 6
:toc: left
:toclevels: 4


== Create RBD Pool

=== Exercise 
Perform the following operations:

* Create a pool `newrbd`  to host some RBDs. The pool will use a replication factor of 2.
* Change the default RBD Image order to be 20 in  `newrbd`
* Verify pool `rbdpool` exists. If not create it

=== Solution

Create the newrbd pool

----
# ceph osd pool create newrbd 8 8 
# ceph osd pool application enable newrbd rbd
# ceph osd pool set newrbd size 2
# ceph osd pool set newrbd min_size 1
----

Change the Image order to be 20

----
# rbd config pool list newrbd | grep rbd_default_order
rbd_default_order                                    22           config
# rbd config pool set newrbd rbd_default_order 20
[root@ceph-node01 ~]# rbd config pool list newrbd | grep rbd_default_order
rbd_default_order                                    20           config
----


[TIP]
====
*rbd_default_order*
This configures the default object size for new images. The value is used as a power of two, meaning default_object_size = 2 ^
rbd_default_order. Configure a value between 12 and 25 (inclusive), translating
to 4KiB lower and 32MiB upper limit.  default value 22 (4MB)
====

Verify rbdpool exists:

----
# ceph osd lspools | grep rbdpool
1 rbdpool
----

== Create RBD Image

=== Exercise

Perform the following operations in pool `newrbd`:

* Create a 256MiB RBD image `testimage`
* Check used space( # rbd -p rbdpool du newrbd/testimage )
* Format the RBD Image with `ext4`
* Copy the content of `/var/log` into the RBD Image in a directory called `batch1`
* Create a snapshot `snap1` for the RBD Image
* Copy the content of `/var/lib/alternatives/` into the RBD Image in a directory called `batch2`
* Create a snapshot `snap2` for the RBD Image

=== Solution

Create a 256MiB RBD image `testimage` and Format the RBD Image with `ext4`

----
# rbd create --pool newrbd --size 256M --image testimage
# rbd -p newrbd info testimage
# rbd -p rbdpool du newrbd/testimage
# rbd map newrbd/testimage
# mkfs.ext4 /dev/rbd0
----

Rest of the steps to follow:

----
# mount /dev/rbd0 /mnt
# mkdir -p /mnt/batch1
# cp -pr /var/log /mnt/batch1/
# rbd snap create newrbd/testimage@snap1
# mkdir -p /mnt/batch2
# cp -pr /var/lib/alternatives/ /mnt/batch2/
# rbd snap create newrbd/testimage@snap2
----

== Export and Import

=== Exercise

Perform the following operations in pool `newrbd`:

* Export as a flat file the differences between the formatted RBD Image and `snap1`
* Export as a flat file the differences between `snap1` and `snap2`
* Import the differences you exported into a RBD Image named `target1` in pool `rbdpool`

=== Solution

We use the `rbd export-diff` command to output to file the differences between
the current image state and snap1

----
#  rbd export-diff newrbd/testimage@snap1 /tmp/diffsnap1.rbd
Exporting image: 100% complete...done.
----

We do the same and capture the differences between snap1 and snap2 into file /tmp/diffsnap1tosnap2.rbd

----
# rbd export-diff --from-snap snap1 newrbd/testimage@snap2 /tmp/diffsnap1tosnap2.rbd
Exporting image: 100% complete...done.
----

With both export files we have a full picture of the state of our image, so we
can merge the exports in a single file with `rbd merge-diff` called
`/tmp/final.rbd` and import the image into the `rbdpool` pool

----
# rbd merge-diff /tmp/diffsnap1.rbd /tmp/diffsnap1tosnap2.rbd /tmp/final.rbd
Merging image diff: 100% complete...done.
# rbd import /tmp/final.rbd rbdpool/target1
Importing image: 100% complete...done.
----

== Clone

=== Exercise

Perform the following operations:

* Create a clone of `newrbd/testimage@snap2` in pool `rbdpool` and name it `clone1`
* Make the clone rbdpool/clone1 an independent RBD Image

=== Solution

Before we can clone an RBD snap we need to protect it, so it can't be deleted

----
# rbd snap protect newrbd/testimage@snap2
# rbd clone newrbd/testimage@snap2 rbdpool/clone1
----

We are goig to `Flaten` the clone so it's and independent RBD image in pool
`rbdpool` we will see that after we flaten the clone it will consume the full
space of the image not only the COW space.

----
# rbd du rbdpool/clone1
# rbd flatten rbdpool/clone1
Image flatten: 100% complete...done.
# rbd du rbdpool/clone1
----

== Cleanup

* Delete all RBD Images
* Delete all pools you have created
