= Cluster Health and PGs 

//++++
//<link rel="stylesheet"  href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/3.1.0/css/font-awesome.min.css">
//++++
:icons: font
:source-language: shell
:numbered:
// Activate experimental attribute for Keyboard Shortcut keys
:experimental:
:source-highlighter: pygments
:sectnums:
:sectnumlevels: 6
:toc: left
:toclevels: 4


== Introduction

It's important to monitor the state of PGs in a Ceph cluster to ensure that data is being properly replicated and that any issues with replication or placement are addressed in a timely manner.

Placement Group (PG) in Ceph is a group of objects that are stored together on the same set of storage devices, known as an OSD (Object Storage Device) cluster. The purpose of a PG is to manage data placement and replication within a Ceph storage cluster. Each object in the Ceph cluster is associated with a specific PG, and each PG is responsible for replicating and distributing its associated objects across multiple OSDs.

PGs are organized into pools, and each pool can have multiple PGs. The number of PGs in a pool is determined by the size of the pool and the desired level of data redundancy. When data is written to a Ceph cluster, it is striped across multiple PGs within a given pool, and each PG then replicates that data across multiple OSDs. This allows for data to be distributed across multiple devices and locations, providing high availability and fault tolerance.

== PG states

- *"creating"* - The PG is being created for the first time and is not yet ready for use.
- *"active+clean"* - The PG is fully functional and has all of its data replicated and available.
- *"active+undersized"* - The PG is fully functional but does not have enough replicas of its data.
- *"active+degraded"* - The PG is fully functional but one or more replicas of its data is missing or unavailable.
- *"active+stale"* - The PG is fully functional but one or more replicas of its data is stale and needs to be updated.
- *"peering"* - The PG is in the process of adjusting its placement and replication settings.
- *"recovering"* - The PG is in the process of recovering missing or unavailable data.
- *"backfill"* - The PG is in the process of adding new replicas to its data.
- *"incomplete"* - The PG does not have enough replicas to function and is waiting for additional nodes to join the cluster.
- *"stale"* - The PG is not currently in use and its data is being moved to other PGs.

It's important to monitor the state of PGs in a Ceph cluster to ensure that data is being properly replicated and that any issues with replication or placement are addressed in a timely manner. Some of the common tools used to monitor the PG states are ceph-pg-status, ceph-pg-dump, and ceph-pg-list.

== PGs and Pools

A pool is a logical collection of PGs, and it is used to manage the data replication and distribution for a specific set of objects. Each pool can have a different number of PGs, and a different replication factor, depending on the desired level of data redundancy. The number of PGs in a pool is determined by the size of the pool and the desired level of data redundancy.

In summary, PGs are responsible for managing the data placement and replication within a Ceph cluster, OSDs are the daemons that run on the storage nodes and are responsible for managing the data stored on those nodes, and pools are the logical collections of PGs that are used to manage the data replication and distribution for a specific set of objects. Each object in the Ceph cluster is associated with a specific PG, which is a part of a specific pool, and each PG is responsible for replicating and distributing its associated objects across multiple OSDs.

== PGs and Peering

The Golden Rule is that no write operation to any PG is acknowledged to a client until it has been persisted by all members of the acting set for that PG. This means that if we can communicate with at least one member of each acting set since the last successful peering, someone will have a record of every (acknowledged) operation since the last successful peering. This means that it should be possible for the current primary to construct and disseminate a new authoritative history.

It is also important to appreciate the role of the OSD map (list of all known OSDs and their states, as well as some information about the placement groups) in the peering process:

When OSDs go up or down (or get added or removed) this has the potential to affect the active sets of many placement groups.

Before a primary successfully completes the peering process, the OSD map must reflect that the OSD was alive and well as of the first epoch in the current interval.

Changes can only be made after successful peering.

Thus, a new primary can use the latest OSD map along with a recent history of past maps to generate a set of past intervals to determine which OSDs must be consulted before we can successfully peer. The set of past intervals is bounded by last epoch started, the most recent past interval for which we know peering completed. The process by which an OSD discovers a PG exists in the first place is by exchanging PG info messages, so the OSD always has some lower bound on last epoch started.

The high level process is for the current PG primary to:

* get a recent OSD map (to identify the members of the all interesting acting sets, and confirm that we are still the primary).
* generate a list of past intervals since last epoch started. Consider the subset of those for which up_thru was greater than the first interval epoch by the last interval epoch’s OSD map; that is, the subset for which peering could have completed before the acting set changed to another set of OSDs.
* Successful peering will require that we be able to contact at least one OSD from each of past interval’s acting set.
* ask every node in that list for its PG info, which includes the most recent write made to the PG, and a value for last epoch started. If we learn about a last epoch started that is newer than our own, we can prune older past intervals and reduce the peer OSDs we need to contact.
* if anyone else has (in its PG log) operations that I do not have, instruct them to send me the missing log entries so that the primary’s PG log is up to date (includes the newest write)..
for each member of the current acting set:

** ask it for copies of all PG log entries since last epoch start so that I can verify that they agree with mine (or know what objects I will be telling it to delete).

** If the cluster failed before an operation was persisted by all members of the acting set, and the subsequent peering did not remember that operation, and a node that did remember that operation later rejoined, its logs would record a different (divergent) history than the authoritative history that was reconstructed in the peering after the failure.

** Since the divergent events were not recorded in other logs from that acting set, they were not acknowledged to the client, and there is no harm in discarding them (so that all OSDs agree on the authoritative history). But, we will have to instruct any OSD that stores data from a divergent update to delete the affected (and now deemed to be apocryphal) objects.

** ask it for its missing set (object updates recorded in its PG log, but for which it does not have the new data). This is the list of objects that must be fully replicated before we can accept writes.

* at this point, the primary’s PG log contains an authoritative history of the placement group, and the OSD now has sufficient information to bring any other OSD in the acting set up to date.

* if the primary’s up_thru value in the current OSD map is not greater than or equal to the first epoch in the current interval, send a request to the monitor to update it, and wait until receive an updated OSD map that reflects the change.

* for each member of the current acting set:

** send them log updates to bring their PG logs into agreement with my own (authoritative history) … which may involve deciding to delete divergent objects.

** await acknowledgment that they have persisted the PG log entries.

* at this point all OSDs in the acting set agree on all of the meta-data, and would (in any future peering) return identical accounts of all updates.

** start accepting client write operations (because we have unanimous agreement on the state of the objects into which those updates are being accepted). Note, however, that if a client tries to write to an object it will be promoted to the front of the recovery queue, and the write willy be applied after it is fully replicated to the current acting set.

** update the last epoch started value in our local PG info, and instruct other active set OSDs to do the same.

** start pulling object data updates that other OSDs have, but I do not. We may need to query OSDs from additional past intervals prior to last epoch started (the last time peering completed) and following last epoch clean (the last epoch that recovery completed) in order to find copies of all objects.

** start pushing object data updates to other OSDs that do not yet have them.
We push these updates from the primary (rather than having the replicas pull them) because this allows the primary to ensure that a replica has the current contents before sending it an update write. It also makes it possible for a single read (from the primary) to be used to write the data to multiple replicas. If each replica did its own pulls, the data might have to be read multiple times.

* once all replicas store the all copies of all objects (that existed prior to the start of this epoch) we can update last epoch clean in the PG info, and we can dismiss all of the stray replicas, allowing them to delete their copies of objects for which they are no longer in the acting set.

* We could not dismiss the strays prior to this because it was possible that one of those strays might hold the sole surviving copy of an old object (all of whose copies disappeared before they could be replicated on members of the current acting set).


== Troubleshooting PGs

Troubleshooting placement group (PG) issues in a Ceph cluster can be a complex process, but there are several tools and techniques that can help.

* Monitor PG states: One of the first things to check when troubleshooting PG
issues is the state of the PGs in the cluster. The `ceph pg dump` command can
be used to view the state of all PGs in the cluster, and `ceph pg <pgid> state` can be used to view the state of a specific PG.

* Check for Stuck PGs: If a PG is stuck in a particular state, it can cause
performance issues or data unavailability. Use the command `ceph pg dump
--format json-pretty` to check for stuck PGs.

----
# ceph pg dump_stuck stale
# ceph pg dump_stuck inactive
# ceph pg dump_stuck unclean
----

* If you receive an active+clean+inconsistent state, this may happen due to an error during scrubbing. Identify the inconsistent placement group(s) by executing the following:

----
# ceph health detail
  HEALTH_ERR 1 pgs inconsistent; 2 scrub errors
  pg 0.6 is active+clean+inconsistent, acting [0,1,2]
  2 scrub errors

# rados list-inconsistent-pg rbd
  ["0.6"]

# rados list-inconsistent-obj 0.6 --format=json-pretty
----

* Query the cluster to determine exactly why the PG is marked down by executing the following: `ceph pg 0.5 query`

* Check for degraded objects: If a PG is in a degraded state, it means that one
or more replicas of the data is missing or unavailable. You can use the `ceph
object map <objectname>` command to check for degraded objects.

* Check for failed OSDs: Failed OSDs can cause issues with data replication and
availability. Use the `ceph osd tree` command to check the status of all OSDs in the cluster

* Check for slow OSDs: Slow OSDs can also cause issues with data replication and
availability. Use `ceph osd perf` command to check the performance of all OSDs in the cluster.

* Check for errors in log files: Reviewing log files can often provide additional
information about the cause of a problem. The `ceph -s` command can be used to view the overall status of the cluster, including any errors or warnings that have been logged.

* Check for network issues: Network issues can cause delays or disruptions in data replication and availability. To check for network issues, you can use tools like ping, traceroute, and netstat.

It's important to identify and resolve PG issues as soon as possible to ensure that data is being properly replicated and that any issues with replication or placement are addressed in a timely manner.

== Cluster Health Status

* *HEALTH_OK:* This indicates that the cluster is fully operational and all of its components are working as expected.

* *HEALTH_WARN:* This indicates that there may be some issues with the cluster, but they do not currently affect its overall functionality. For example, some OSDs may be down or some monitors may be unreachable, but the cluster is still able to function.

* *HEALTH_ERR:* This indicates that there are serious issues with the cluster that are affecting its functionality. For example, a critical number of OSDs may be down or there may be a problem with the metadata servers.

* *HEALTH_FAILED:* This indicates that the cluster is not operational and that data may be at risk. This can happen if all of the monitors are down or if there is a problem with the entire cluster that cannot be easily resolved.

* *HEALTH_UNKNOWN:* This indicates that the status of the cluster is unknown. This can happen if the cluster is not configured properly or if there is a problem with the communication between the different components.

It is important to monitor the health status of a Ceph cluster regularly, and to take appropriate action if the status changes to HEALTH_ERR or HEALTH_FAILED. This may involve adding or replacing hardware, adjusting the configuration of the cluster, or performing other types of maintenance to keep the cluster running smoothly.
