= Ceph Confguration Parameters

//++++
//<link rel="stylesheet"  href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/3.1.0/css/font-awesome.min.css">
//++++
:icons: font
:source-language: shell
:numbered:
// Activate experimental attribute for Keyboard Shortcut keys
:experimental:
:source-highlighter: pygments
:sectnums:
:sectnumlevels: 6
:toc: left
:toclevels: 4

== Introduction

Every Ceph daemon, process, and library accesses its configuration from one of these sources:
* The compiled-in default value
* The centralized configuration database
* Configuration file `ceph.conf` that is usually saved in `/etc/ceph.conf`

One of the first things a Ceph process does on startup is parse the configuration options provided via the command line, environment, and local configuration file. The process will then contact the monitor cluster to retrieve configuration stored centrally for the entire cluster. Once a complete view of the configuration is available, the daemon or process startup will proceed.

== Ceph Configuration Sections

Ceph organizes confi settings into groups, doesn't matter if stored in the
ceph.conf or in the configuration database

* The [global] section stores general configuration that is common to all services
* The [osd] section for the OSD daemons.
* The [mds] section for the Metadata Servers (MDS).
* The [mon] section for the Monitors (MON).
* The [mgr] section for the Managers (MGR).
* The [mds] section for the Metadata Servers (MDS).
* The [client] section for all the Ceph clients. (RGW config is included in the client section)


To get current config from the ceph config database the for mds filesystem
called newfs and query the parameter mds_cache_memory_limit

----
# ceph config get mds.newfs mds_cache_memory_limit
4294967296
----

To get current config from the ceph config database to a specific MDS daemon
called proxy01.cvopqn and query the parameter mds_cache_memory_limit

----
# ceph config get mds.newfs.proxy01.cvopqn mds_cache_memory_limit
4294967296
----


== Using the Ceph centralized configuration database

The Ceph Centralized configuration database is the prefered way of configuring
Ceph parameters when we want to make them permanent, the values for the config
database are stored in the Monitors.

Use ceph config commands to query the database and view configuration information.

* `ceph config ls` list all ceph configuration settings. Good for when you don't remember the exact parameter you want to modify

----
# ceph config ls | grep pool_delete
mon_allow_pool_delete
mon_fake_pool_delete
----

* `ceph config get`. Once we get the config setting we want to modify from `ceph config ls` we can query its current value with `ceph config get`

----
# ceph config get mon mon_allow_pool_delete
true
----

* `ceph config set`, Now that we have the current value we can use `set` to * modify the parameter to a new value

----
# ceph config set mon mon_allow_pool_delete true
----

* `ceph config dump`, show the cluster configuration database parameters. Good to check what parameters have been changed from their default value

----
# ceph config dump
WHO                                         MASK  LEVEL     OPTION                                     VALUE                                                                                                             RO
global                                            basic     container_image                            registry.redhat.io/rhceph/rhceph-5-rhel8@sha256:04c39425bc9e05e667ebe23513847b905b5998994cc95572c6a4549b8826bd81  *
global                                            advanced  mon_max_pg_per_osd                         512
global                                            dev       rbd_config_pool_override_update_timestamp  1677145632
global                                            advanced  rbd_default_order                          20
  mon                                             advanced  auth_allow_insecure_global_id_reclaim      false
  mon                                             advanced  mon_allow_pool_delete                      true
  mon                                             advanced  mon_max_pg_per_osd                         512
  mon                                             advanced  public_network                             192.168.56.0/24                                                                                                   *
  mgr                                             advanced  mgr/cephadm/container_init                 True                                                                                                              *
  mgr                                             advanced  mgr/cephadm/migration_current              5                                                                                                                 *
  mgr                                             advanced  mgr/dashboard/ALERTMANAGER_API_HOST        http://proxy01.example.com:9093                                                                                   *
  mgr                                             advanced  mgr/dashboard/GRAFANA_API_SSL_VERIFY       false                                                                                                             *
  mgr                                             advanced  mgr/dashboard/GRAFANA_API_URL              https://proxy01.example.com:3000                                                                                  *
  mgr                                             advanced  mgr/dashboard/PROMETHEUS_API_HOST          http://proxy01.example.com:9095                                                                                   *
  mgr                                             advanced  mgr/dashboard/RGW_API_ACCESS_KEY           71M1JD7FSWU1BR2UYARK                                                                                              *
  mgr                                             advanced  mgr/dashboard/RGW_API_SECRET_KEY           CZ7t4uJySQvqxIeLYLPxCgDq60EAGRQf8372mjAi                                                                          *
  mgr                                             advanced  mgr/dashboard/ssl_server_port              8443                                                                                                              *
  mgr                                             advanced  mgr/orchestrator/orchestrator              cephadm
  osd                                             advanced  osd_memory_target_autotune                 true
    mds.newfs                                     basic     mds_join_fs                                newfs
    mds.newfs.proxy01.cvopqn                      basic     mds_cache_memory_limit                     8589934592
    client.rgw.objectgw.ceph-node02.dunkir        basic     rgw_frontends                              beast port=8080                                                                                                   *
----


== The new role of ceph.conf

In recent versions of ceph, the configuration files are stored in the
centralized configuration database.

But a handful of settings still need to be stored in local configuration files
because they affect the ability to connect to the monitors, authenticate, and
fetch configuration information. In most cases this is limited to the mon_host
option. 

*For Example*

----
# cat /etc/ceph/ceph.conf
[global]
	fsid = 7e5c9c9a-9d70-11ed-9c09-2cc26078e4ef
	mon_host = [v2:192.168.56.61:3300/0,v1:192.168.56.61:6789/0] [v2:192.168.56.62:3300/0,v1:192.168.56.62:6789/0] [v2:192.168.56.63:3300/0,v1:192.168.56.63:6789/0]
----

== Changing Configuration options on the fly

Options can be set temporarily by using the tell or daemon interfaces on the Ceph CLI. These override values are ephemeral, which means that they affect only the current instance of the daemon and revert to persistently configured values when the daemon restarts.

From any node in the cluster

----
$ ceph tell <name> config set <option> <value>
# ceph tell osd.123 config set debug_osd 20
----

Also we have `ceph daemon` from the node were the services is running

----
# ceph --admin-daemon /var/run/ceph/ceph-client.rgw.<name>.asok config set debug_rgw 20
----

or 

----
# ceph daemon osd.4 config set debug_osd 20
----

== View Run Time Configuration settings

ou can see the current options set for a running daemon with the ceph config show command.

----
# ceph config show osd.0
# ceph config show osd.0 debug_osd
----

Also the default values can be listed

----
# ceph config show-with-defaults osd.0
----
